kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deleteRoleBinding
  namespace: delete-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deleteRole
subjects:
- kind: Group
  namespace: delete-access
  name: 75c59b29-f3f4-41bd-8e5e-1e92ecf70b48